Travel/Areas/Admin/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Service.Services;
using Service.Services.Interfaces;
using Service.ViewModels.Hotel;
using Service.ViewModels.HotelImages;
using System.Threading.Tasks;

namespace Travel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HotelController : Controller
    {
        private readonly IHotelService _hotelService;
        private readonly ICityService _cityService;
        private readonly IHotelImageService _hotelImageService;
        public HotelController(IHotelService hotelService, ICityService cityService, IHotelImageService hotelImageService)
        {
            _hotelService = hotelService;
            _cityService = cityService;
            _hotelImageService = hotelImageService;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _hotelService.GetAllHotel());
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            if(id == null)
            {
                return BadRequest();
            }
            var data = await _hotelService.GetHotelDetail(id);
            if(data == null)
            {
                return NotFound();
            }
            return View(data);  
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var cities = await _cityService.GetAll();
            ViewBag.Cities = cities.Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.Id.ToString()
            }).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(HotelCreateVM model)
        {
            var cities = await _cityService.GetAll();
            ViewBag.Cities = cities.Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.Id.ToString()
            }).ToList();
            if (model == null)
            {
                return BadRequest();
            }
            if (model.Images == null || model.Images.Count() < 5)
            {
                ModelState.AddModelError("Images", "Please upload at least 5 images.");
                return View(model);
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if(model.Images.Count() < 5)
            {
                ModelState.AddModelError("Images", "Add at least 5 images!");
                return View(model);
            }
            await _hotelService.Create(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var data = await _hotelService.GetHotelDetail(id);
            if (data == null)
            {
                return NotFound();
            }
            await _hotelService.Delete(id);
            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var cities = await _cityService.GetAll();
            ViewBag.Cities = cities.Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.Id.ToString()
            }).ToList();
            if (id == null)
            {
                return BadRequest();
            }
            var existData = await _hotelService.GetHotelDetail(id);
            if (existData == null)
            {
                return NotFound();
            }
            HotelEditVM hotelEditVM = new HotelEditVM()
            {
                Id = existData.Id,
                Name = existData.Name,
                Address = existData.Address,
                Description = existData.Description,
                StarCount = existData.StarCount,
                SpaSauna = existData.SpaSauna,
                Restaurant = existData.Restaurant,
                AirConditioning = existData.AirConditioning,
                AirportTransport = existData.AirportTransport,
                CityId = existData.CityId,
                FitnessCenter = existData.FitnessCenter,
                Parking = existData.Parking,

                ExistImages = existData.ImageUrls.Select(m=>new HotelImageVM
                {
                    HotelId = m.Id,
                    Id = m.Id,
                    IsMain = m.IsMain,
                    Url = m.Url
                })
            };
            return View(hotelEditVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, HotelEditVM model)
        {
            var cities = await _cityService.GetAll();
            ViewBag.Cities = cities.Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.Id.ToString()
            }).ToList();
            if (id == null)
            {
                return BadRequest();
            }
            var data = await _hotelService.GetHotelDetail(id);
            if (data == null)
            {
                return NotFound();
            }
            ModelState.Remove("ExistImages");
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _hotelService.Update(id, model);
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public async Task<IActionResult> DeleteImage(int id)
        {
            if(id == null)
            {
                return BadRequest();
            }
            await _hotelImageService.Delete(id);
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> SetMain(int imageId, int hotelId)
        {
            if (imageId == null)
            {
                return BadRequest();
            }
            await _hotelImageService.SetMain(imageId, hotelId);
            return Ok();
        }

        [HttpGet]
        public IActionResult AddImages(int id)
        {
            AddImageVM vm = new AddImageVM()
            {
                HotelId = id,
            };
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddImages(AddImageVM model)
        {
            if(model == null)
            {
                return BadRequest();
            }
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            await _hotelImageService.AddImage(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Change(int id)
        {
            if(id == null)
            {
                return BadRequest();
            }
            var existImage = await _hotelImageService.GetById(id);
            if(existImage == null)
            {
                return NotFound();
            }
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Change(int id, ChangeImageVM model)
        {
            var existData = await _hotelImageService.GetById(id);
            if(existData == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _hotelImageService.Change(id, model);
            return RedirectToAction("Index");
        }
    }
}

Travel/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;

namespace Reservation_Final.Controllers
{
    public class AboutController : Controller
    {
        private readonly IStaffService _staffService;
        public AboutController(IStaffService staffService)
        {
            _staffService = staffService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _staffService.GetAll());
        }
        
    }
}

Travel/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;
using Service.ViewModels.Blog;
using System.Threading.Tasks;

namespace Reservation_Final.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IBlogCategoryService _blogCategoryService;
        public BlogController(IBlogService blogService, IBlogCategoryService blogCategoryService)
        {
            _blogService = blogService;
            _blogCategoryService = blogCategoryService;
        }
        public async Task<IActionResult> Index()
        {
            BlogAndCategoryVM blogAndCategoryVM = new BlogAndCategoryVM()
            {
                BlogCategories = await _blogCategoryService.GetAllBlogCategories(),
                Blogs = await _blogService.GetAllBlogsWithCategoriesAndImages()
            };
            return View(blogAndCategoryVM);
        }
        public async Task<IActionResult> BlogDetail(int id)
        {
            BlogAndCategoryVM blogAndCategoryVM = new BlogAndCategoryVM()
            {
                BlogCategories = await _blogCategoryService.GetAllBlogCategories(),
                Blog = await _blogService.GetBlogById(id)
            };
            return View(blogAndCategoryVM);
        }
        public async Task<IActionResult> BlogsByCategory(int id)
        {
            BlogAndCategoryVM blogAndCategoryVM = new BlogAndCategoryVM()
            {
                BlogCategories = await _blogCategoryService.GetAllBlogCategories(),
                Blogs = await _blogService.GetAllByCategoryId(id)
            };
            return View(blogAndCategoryVM);
        }
    }
}

Travel/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;
using Service.ViewModels.Messages;

namespace Reservation_Final.Controllers
{
    public class ContactController : Controller
    {
        private readonly IMessageService _messageService;
        public ContactController(IMessageService messageService)
        {
            _messageService = messageService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddMessage(MessageCreateVM model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index",model);
            }
            await _messageService.Create(model);
            return RedirectToAction("Index");
        }
    }
}

Travel/Controllers/FAQController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services.Interfaces;
using System.Threading.Tasks;

namespace Reservation_Final.Controllers
{
    public class FAQController : Controller
    {
        private readonly IFAQService _faqService;
        public FAQController(IFAQService faqService)
        {
            _faqService = faqService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _faqService.GetAll());
        }

    }
}

Travel/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Service.Services.Interfaces;
using Service.ViewModels;
using Service.ViewModels.Hotel;
using System.Threading.Tasks;

namespace Reservation_Final.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelService _hotelService;
        private readonly ICommentService _commentService;
        private readonly IHotelImageService _hotelImageService;

        public HotelController(IHotelService hotelService, 
                               ICommentService commentService, 
                               IHotelImageService hotelImageService)
        {
            _hotelService = hotelService;
            _commentService = commentService;
            _hotelImageService = hotelImageService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _hotelService.GetAllHotel());
        }
        public async Task<IActionResult> Detail(int id)
        {
            var wishlistJson = HttpContext.Session.GetString("wishlist");
            List<int> wishlist = new();

            if (!string.IsNullOrEmpty(wishlistJson))
            {
                wishlist = JsonConvert.DeserializeObject<List<int>>(wishlistJson);
            }

            ViewBag.Wishlist = wishlist;
            return View(await _hotelService.GetHotelDetail(id));
        }
        public async Task<IActionResult> Filter(FilterVM filter)
        {
            return View(await _hotelService.HotelFilter(filter));
        }
        public async Task<IActionResult> FilterByCity(int id)
        {
            return View(await _hotelService.HotelFilterByCity(id));
        }
        public async Task<IActionResult> Search(SearchVM query)
        {
            return View(await _hotelService.Search(query));
        }
        public async Task<IActionResult> ShowMore(int hotelId, int skip)
        {
            return Ok(await _commentService.ShowMore(hotelId, skip));
        }
        public async Task<IActionResult> ShowAllImages(int id)
        {
            return View(await _hotelImageService.GetAllByHotelId(id));
        }
    }
}

Travel/Views/Hotel/ShowAllImages.cshtml
@model IEnumerable<HotelImageVM>
@{
    ViewData["Title"] = "Hotel Detail";
}
@inject ISettingService _settingService
@{
    var datas = (await _settingService.GetSettings()).ToDictionary(x => x.Key, x => x.Value);
}
@section css {
    <link rel="stylesheet" href="~/assets/css/HotelDetail/style.css">
}
<main>
    <section id="nav"
             style="background-image: url('@Url.Content("~/assets/images/home/banner-search-form-min.png")'); background-size: cover;">
        <div class="navbar">
            <div class="cus-container">
                <div class="row align-items-center line">
                    <div class="col-md-2 left">
                        <div class="menuIcon d-none">
                            <i class="fa-solid fa-bars"></i>
                        </div>
                        <div class="logo">
                            <a asp-controller="Home" asp-action="Index">
                                <picture>
                                    <source media="(max-width: 990px)" srcset="@datas["blackLogo"]">
                                    <img class="logo" src="@datas["logo"]">
                                </picture>
                            </a>
                        </div>

                    </div>
                    <div class="col-md-7 midd">
                        <ul>
                            <li>
                                <a asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li>
                                <a asp-controller="Hotel" asp-action="Index">Hotels</a>
                            </li>
                            <li>
                                <a asp-controller="About" asp-action="Index">About</a>
                            </li>
                            <li>
                                <a asp-controller="Blog" asp-action="Index">Blog</a>
                            </li>
                            <li>
                                <a asp-controller="Contact" asp-action="Index">Contact</a>
                            </li>
                            <li>
                                <a asp-controller="FAQ" asp-action="Index">FAQ</a>
                            </li>
                            @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                            {
                                <li>
                                    <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a>
                                </li>
                            }
                        </ul>
                    </div>

                    <div class="col-md-3 right">
                        <div class="currency">
                            <span id="currency">EUR</span>
                            <i class="fa-solid fa-angle-down curicon"></i>
                            <i class="fa-solid fa-angle-up curicon_ d-none"></i>
                        </div>
                        <div class="basket">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="Wishlist" asp-action="Index" style="text-decoration:none; color:black">
                                    <div class="circle" style="position:relative">
                                        <i class="fa-regular fa-heart like-iconn" style="font-size:20px !important"></i>
                                        <div class="count" style="width:17px; height:17px; border-radius:50%; background-color:#05bdeb; display:flex; align-items:center; justify-content:center; position:absolute; top:4px; right: 6px">
                                            <span id="wishlist-count" style="font-size:11px">0</span>
                                        </div>
                                    </div>
                                </a>
                            }
                            else
                            {
                                <a style="text-decoration:none; color:black">
                                    <div class="circle without" style="position:relative">
                                        <i class="fa-regular fa-heart like-iconn" style="font-size:20px !important"></i>
                                        <div class="count" style="width:17px; height:17px; border-radius:50%; background-color:#05bdeb; display:flex; align-items:center; justify-content:center; position:absolute; top:4px; right:6px">
                                            <span id="wishlist-count" style="font-size:11px">0</span>
                                        </div>
                                    </div>
                                </a>
                                <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
                                <script>

                                    let item = document.querySelector(".without").addEventListener("click", function(){
                                        Swal.fire("Login to your account!");
                                    })
                                </script>
                            }
                            <script>
                                function updateWishlistCount() {
                                        fetch('https://localhost:7107/WishList/GetCount')
                                            .then(response => {
                                                if (!response.ok) throw new Error('Network response was not ok');
                                                return response.json();
                                            })
                                            .then(data => {
                                                const countElem = document.getElementById('wishlist-count');
                                                if (countElem) {
                                                    countElem.textContent = data.result;
                                                }
                                            })
                                            .catch(error => console.error('Fetch error:', error));
                                    }


                                    updateWishlistCount();
                            </script>
                        </div>
                        <div class="profile">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <a asp-controller="Account" asp-action="Login">
                                    <div class="circle">
                                        <i class="fa-regular fa-user" style="color:black"></i>
                                    </div>
                                </a>
                            }
                            else
                            {
                                <a href="" style="pointer-events: none;">
                                    <div class="circle">
                                        <i class="fa-regular fa-user" style="color:black"></i>
                                    </div>
                                </a>
                            }
                        </div>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="login-info">
                                <span style="color:white">@User.Identity.Name</span>
                                <form method="post" asp-controller="Account" asp-action="LogOut">
                                    <button type="submit" class=" btn btn-primary ">Log out</button>
                                </form>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="controller-name">
            <span class="home">Home</span>
            <span class="icon"><i class="fa-solid fa-circle"></i></span>
            <span class="name">Hotel Images</span>
        </div>
        <div class="currency-tab d-none">
            <ul>
                <li class="li">
                    USD
                </li>
                <li class="li">
                    EUR
                </li>
                <li class="li">
                    AZN
                </li>
            </ul>
        </div>
        
    </section>
    <div class="container my-4">

        <div class="image-grid">

            @foreach (var img in Model)
            {
                <figure class="image-item" >
                    <img src="@img.Url" style="width:300px; height:280px" />
                </figure>
            }
        </div>
    </div>

</main>
<style>
    .image-grid {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
        gap: 1rem; 
    }


    .image-item img {
        width: 100%; 
        height: auto; 
        border-radius: 15px;
        object-fit: cover; 
        box-shadow: 0 2px 6px rgba(0,0,0,.15); 
    }


    .container {
        padding-left: 2rem;
        padding-right: 2rem;
    }
</style>
<script src="~/assets/js/hotelDetail/script.js"></script>